name: Niels van der Vlies
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

paginate: 5
paginate_path: "page:num"

excerpt_separator: <!--more-->

navigation:
 - text: Home
   url: /
 - text: Archive
   url: /archive/
 - text: Contact
   url: /contact/

url: "http://nvdvlies.github.io"
baseurl: "/"